version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm cache clean --force
      - npm install
  build:
    commands:
      - npm run build

      #- aws s3 rm s3://$S3_BUCKET_NAME --recursive --exclude 'core/*'

      #- aws s3 sync ./dist s3://$S3_BUCKET_NAME --cache-control max-age=604800 --exclude 'index.html' --exclude 'core/*'

      #- AWS_MAX_ATTEMPTS=10 aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"


